export const GET_RECIPES = "GET_RECIPES";
export const SEARCH_RECIPES = "SEARCH_RECIPES";
export const GET_ONE_RECIPE = "GET_ONE_RECIPE";
export const SELECT_FAVORITE_RECIPE = "SELECT_FAVORITE_RECIPE";
 
export const DELETE_RECIPE = "DELETE_RECIPE";
export const RECIPES_LOADING = "RECIPES_LOADING";

/** AUTENTICATION & REGISTRATION PROCESS **/
// export const USER_LOADING = "USER_LOADING";
// export const USER_LOADED = "USER_LOADED";
// export const AUTH_ERROR = "AUTH_ERROR";
// export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
// export const LOGIN_FAIL = "LOGIN_FAIL";
// export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
// export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
// export const REGISTER_FAIL = "REGISTER_FAIL";

/**
 * ERROR REDUCER [GET ERR - PUT IN STATE - AND CLEAR THEM IF WE WANT]
 */
export const GET_ERRORS = "GET_ERRORS";
export const CLEAR_ERRORS = "CLEAR_ERRORS";