export const recipeDetails = [
  {
    publisher: "Two Peas and Their Pod",
    f2f_url: "http://food2fork.com/view/54419",
    ingredients: [
      "1/2 cup quinoa, rinsed",
      "1 cup water",
      "1 tablespoon olive oil",
      "1 small onion, chopped",
      "3 cloves garlic, minced",
      "1 jalapeno pepper, diced",
      "1 large carrot, peeled and chopped",
      "2 celery stalks, chopped",
      "1 green bell pepper, chopped",
      "1 red bell pepper, chopped",
      "1 medium zucchini, chopped",
      "2 (15 ounce) cans black beans, drained and rinsed",
      "1 (15 ounce) can red kidney beans, drained and rinsed",
      "3 (15 ounce) cans diced tomatoes",
      "1 (15 ounce) can tomato sauce",
      "2-3 tablespoons chili powder, depending on your taste (we used 3)",
      "1 tablespoon ground cumin",
      "Salt and black pepper, to taste",
      "Optional toppings: green onions, avocado slices, cheese, sour cream, Greek yogurt, chips, crackers, etc."
    ],
    source_url: "http://www.twopeasandtheirpod.com/vegetarian-quinoa-chili/",
    recipe_id: "54419",
    image_url: "http://static.food2fork.com/quinoachili15b76.jpg",
    social_rank: 99.9999999999998,
    publisher_url: "http://www.twopeasandtheirpod.com",
    title: "Vegetarian Quinoa Chili"
  },
  {
    publisher: "Cookin Canuck",
    f2f_url: "http://food2fork.com/view/acf219",
    ingredients: [
      "1 \u00bd cans (15 oz. each) Bush\u2019s Cannellini Beans, drained and rinsed",
      "1 roasted red bell pepper (2 halves), roughly chopped",
      "\u00bd medium yellow onion, grated",
      "2 cloves garlic, minced",
      "\u00bc cup chopped Italian parsley",
      "1 \u00bd tsp dried oregano",
      "1 egg",
      "\u00bd cup dried breadcrumbs (see note)",
      "\u00bd tsp kosher salt",
      "\u00bd tsp freshly ground black pepper",
      "3 cups marinara sauce (your favorite kind)",
      "Parmesan cheese for grating",
      "Cooked spaghetti"
    ],
    source_url:
      "http://www.cookincanuck.com/2011/11/cannellini-bean-vegetarian-meatballs-with-tomato-sauce-recipe/",
    recipe_id: "acf219",
    image_url: "http://static.food2fork.com/6297474882_342f91744da59f.jpg",
    social_rank: 99.99999999999531,
    publisher_url: "http://www.cookincanuck.com",
    title: "Cannellini Bean Vegetarian \u201cMeatballs\u201d with Tomato Sauce"
  },
  {
    publisher: "The Pioneer Woman",
    f2f_url: "http://food2fork.com/view/46949",
    ingredients: [
      "2 teaspoons Peanut Or Olive Oil",
      "1 package (about 12-14 Oz. Size) Firm Tofu",
      "2 ears Corn (or 1 1/2 Cups Frozen Corn Kernels)",
      "1/4 teaspoon Chili Powder (more To Taste)",
      "1/4 cup Soy Sauce",
      "Romaine Lettuce Hearts",
      "2 whole Avocados, Sliced",
      "1 teaspoon Balsamic Vinegar (optional)"
    ],
    source_url:
      "http://thepioneerwoman.com/cooking/2012/02/vegetarian-lettuce-wraps/",
    recipe_id: "46949",
    image_url: "http://static.food2fork.com/wraps831c.jpg",
    social_rank: 99.99999999998658,
    publisher_url: "http://thepioneerwoman.com",
    title: "Vegetarian Lettuce Wraps"
  },
  {
    publisher: "Simply Recipes",
    f2f_url: "http://food2fork.com/view/37121",
    ingredients: [
      "1 1/2 pound cremini mushrooms, roughly chopped",
      "1/2 pound shiitake mushrooms, roughly chopped",
      "Salt",
      "1 generous cup of chopped onions",
      "1/4 cup olive oil plus more for keeping the noodles from sticking to each other",
      "4 cloves garlic, chopped (about 4 teaspoons)",
      "1 6-ounce can tomato paste",
      "2 cups tomato sauce",
      "1 28-ounce can crushed tomatoes (I recommend Muir Glen brand with added basil)",
      "1 cup water",
      "1 Tbsp dried thyme",
      "1/2 teaspoon red pepper flakes",
      "1 Tbsp sugar",
      "2 10-ounce boxes frozen chopped spinach, thawed, squeezed in clean towel of excess moisture",
      "1 lb lasagna noodles (16 to 20 noodles)",
      "1 15-or-16-ounce container of ricotta cheese",
      "1/4 cup chopped fresh basil",
      "1/4 pound pecorino or parmesan cheese, grated (about 1 cup)",
      "1 pound shredded mozzarella cheese (about 4 cups)",
      "Special equipment needed: 1 large casserole pan, preferably 10x15-inches\n"
    ],
    source_url:
      "http://www.simplyrecipes.com/recipes/vegetarian_spinach_and_mushroom_lasagna/",
    recipe_id: "37121",
    image_url:
      "http://static.food2fork.com/vegetarianspinachmushroomlasagnaa520300x200b716718e.jpg",
    social_rank: 99.99999956133722,
    publisher_url: "http://simplyrecipes.com",
    title: "Vegetarian Spinach and Mushroom Lasagna"
  },
  {
    publisher: "Cookie and Kate",
    f2f_url: "http://food2fork.com/view/3fc975",
    ingredients: [
      "6 cups low sodium vegetable broth",
      "1 medium red onion, chopped",
      "2 tablespoons peeled and minced fresh ginger",
      "4 cloves garlic, minced",
      "1 teaspoon salt",
      "1 bunch collard greens (or kale), ribs removed and leaves chopped into 1-inch strips",
      "¾ cup unsalted peanut butter (chunky or smooth)",
      "½ cup tomato paste*",
      "Hot sauce, like sriracha (AKA rooster sauce)",
      "¼ cup roughly chopped peanuts, for garnish"
    ],
    source_url: "http://cookieandkate.com/2013/west-african-peanut-soup/",
    recipe_id: "3fc975",
    image_url: "http://static.food2fork.com/westafricanpeanutsoupa5cc.jpg",
    social_rank: 99.99999972298735,
    publisher_url: "http://cookieandkate.com",
    title: "All Recipes"
  },
  {
    publisher: "101 Cookbooks",
    f2f_url: "http://food2fork.com/view/47990",
    ingredients: [
      "Roasted Pumpkin Salad",
      "- A roasted pumpkin salad made with wild rice, tiny, caramelized red onions drizzled with a simple, honey-kissed, creamy sunflower seed dressing.",
      "Raw Tuscan Salad",
      "- A red chile spiked, shredded raw kale salad tossed in a vibrant, lemony-pecorino dressing.",
      "Kale and Olive Oil Mashed Potatoes",
      "- A favorite mashed potato recipe and slight twist on a classic - creamy mashed potatoes flecked with finely chopped greens and garlic. Adding a green like kale, and golden threads of drizzled olive oil is a great way to add color and nutritional umph to America's favorite starch-packed side dish.",
      "Vibrant Tasty Green Beans",
      "- A favorite green bean recipe - dill, green beans, leeks, salt and olive oil. That's it - five ingredients, one skillet - tasty green beans.",
      "Roasted Delicata Squash Salad",
      "- So tasty! Pretty, scalloped-edged cross-cuts of the delicata squash, a few small potatoes, chopped kale, radishes, Marcona almonds - and a bold miso harissa dressing.",
      "Quinoa Skillet Bread",
      "- If you're ready to switch it up a bit, this is a completely over-the-top alternative to your favorite corn bread recipe. Or, better put - a rustic, minimally structured, custard-topped, crusty-edged, herb-scented corn-quinoa skillet bread.",
      "Vanilla Mashed Sweet Potatoes",
      "- Those of you who are long-time readers are likely tired of hearing out this one - but I love it. Plump vanilla beans, cream, orange zest, and butter are combined with sweet potatoes that have been roasted in the oven. A quick whirl in the food processor produces a smooth, creamy, subtly sweet puree haunted by the delicious vanilla and citrus undertones. The consistency is that of a thick frosting.",
      "Hazelnut & Chard Ravioli Salad",
      "- I made this last year and it makes a great vegetarian main dish. Plump raviolis tossed with toasted hazelnuts, sauteed ribbons of chard, and caramelized onions are at the heart of this ravioli salad recipe. It's finished off with a dusting of cheese, snipped chives, and lemon zest. You can prepare most of the components ahead of time.",
      "Spice-kissed Pumpkin Pie",
      "- Favorite, easy pumpkin pie recipe. Made from a rich, roasted pumpkin and coconut milk base, and baked in a hazelnut-lined crust - delicious!",
      "Yeast-raised Cornbread",
      "- Not your typical cornbread recipe. This is a yeast-leavened corn bread recipe, heavily flecked with kernels of bright yellow corn and generously spiked with chives. Perfect for stuffing and soup-dunking.",
      "Golden-Crusted Brussels Sprouts",
      "- A quick and easy brussels sprouts recipe that will convert the biggest skeptics. Vibrant green, tender brussels sprouts that become deeply golden and crusty where they touch the pan, dusted with cheese.",
      "Shredded Brussels Sprouts & Apples",
      "- Another favorite way to cook brussels sprouts. Shredded brussels sprout ribbons, apples, garlic, pine nuts, and tofu in a skillet with a hint of maple syrup.",
      "Thai-spiced Pumpkin Soup",
      "- This Thai-spiced Pumpkin Soup couldn't be easier to make - roasted winter squash, coconut milk, Thai red curry paste, and sea salt come together in a pot of vibrant, rich, flavorful soup. Total crowd pleaser.",
      "Cornmeal Crunch",
      "- This is what happens when you cook a pot of cornmeal until it is thick and creamy. Add a bit off cheese, some deeply caramelized onions, spread it in a pan, drizzle generously with olive oil and bake until the bottom and sides are deeply golden and crunchy."
    ],
    source_url:
      "http://www.101cookbooks.com/archives/vegetarian-thanksgiving-recipes-recipe.html",
    recipe_id: "47990",
    image_url:
      "http://static.food2fork.com/vegetarian_thanksgiving_recipesf594.jpg",
    social_rank: 99.99999810317004,
    publisher_url: "http://www.101cookbooks.com",
    title: "Vegetarian Thanksgiving Recipes"
  },
  {
    publisher: "Cookie and Kate",
    f2f_url: "http://food2fork.com/view/f1898b",
    ingredients: [
      "2 tablespoons olive oil",
      "1 medium red onion, chopped",
      "2 red bell peppers, chopped",
      "1 small butternut squash (1½ pounds or less), peeled and chopped into ½-inch cubes",
      "4 garlic cloves, pressed or minced",
      "1 tablespoon chili powder",
      "½+ tablespoon chopped chipotle pepper in adobo* (start with ½ tablespoon and add more to taste, I thought mine was just right with 1 tablespoon)",
      "1 teaspoon ground cumin",
      "¼ teaspoon ground cinnamon",
      "1 bay leaf",
      "2 cans (15 ounces each) black beans, rinsed and drained, or 3 cups cooked black beans",
      "1 small can (14 ounces) diced tomatoes, including the liquid**",
      "2 cups vegetable broth (or one 14-ounce can)",
      "Salt, to taste",
      "2 Avocados from Mexico, diced",
      "3 corn tortillas for crispy tortilla strips (or substitute crumbled tortilla chips)",
      "Optional additional garnishes: Chopped fresh cilantro and/or red pepper flakes"
    ],
    source_url:
      "http://cookieandkate.com/2012/butternut-squash-chipotle-chili-with-avocado/",
    recipe_id: "f1898b",
    image_url:
      "http://static.food2fork.com/vegetarianbutternutsquashchilirecipe1b9b1.jpg",
    social_rank: 99.99999971392758,
    publisher_url: "http://cookieandkate.com",
    title: "All Recipes"
  },
  {
    publisher: "All Recipes",
    f2f_url: "http://food2fork.com/view/32496",
    ingredients: [
      "1 tablespoon olive oil",
      "1/2 medium onion, chopped",
      "2 bay leaves",
      "1 teaspoon ground cumin",
      "2 tablespoons dried oregano",
      "1 tablespoon salt",
      "2 stalks celery, chopped",
      "2 green bell peppers, chopped",
      "2 jalapeno peppers, chopped",
      "3 cloves garlic, chopped",
      "2 (4 ounce) cans chopped green chile peppers, drained",
      "2 (12 ounce) packages vegetarian burger crumbles",
      "3 (28 ounce) cans whole peeled tomatoes, crushed",
      "1/4 cup chili powder",
      "1 tablespoon ground black pepper",
      "1 (15 ounce) can kidney beans, drained",
      "1 (15 ounce) can garbanzo beans, drained",
      "1 (15 ounce) can black beans",
      "1 (15 ounce) can whole kernel corn"
    ],
    source_url:
      "http://allrecipes.com/Recipe/The-Best-Vegetarian-Chili-In-The-World/Detail.aspx",
    recipe_id: "32496",
    image_url: "http://static.food2fork.com/1765412971.jpg",
    social_rank: 99.99999070660462,
    publisher_url: "http://allrecipes.com",
    title: "The Best Vegetarian Chili in the World"
  },
  {
    publisher: "101 Cookbooks",
    f2f_url: "http://food2fork.com/view/48053",
    ingredients: [
      "3 cups cooked black lentils",
      "4 large eggs",
      "1/2 teaspoon fine-grain sea salt",
      "1 onion, finely chopped",
      "1 cup toasted fine (whole-grain) bread crumbs",
      "1 tablespoon extra-virgin olive oil (or clarified butter)"
    ],
    source_url:
      "http://www.101cookbooks.com/archives/vegetarian-lentil-burgers-recipe.html",
    recipe_id: "48053",
    image_url: "http://static.food2fork.com/lentilburgerrecipe_07405f.jpg",
    social_rank: 99.99999031231295,
    publisher_url: "http://www.101cookbooks.com",
    title: "Vegetarian Lentil Burgers"
  },
  {
    publisher: "101 Cookbooks",
    f2f_url: "http://food2fork.com/view/47960",
    ingredients: [
      "1 tablespoon extra virgin olive oil",
      "2 large onions, chopped",
      "1/2 teaspoon fine-grain sea salt",
      "2 cups dried split green peas, picked over and rinsed",
      "5 cups water",
      "juice of 1/2 lemon (reserve the zest)",
      "a few pinches of smoked paprika",
      "more olive oil to drizzle"
    ],
    source_url:
      "http://www.101cookbooks.com/archives/vegetarian-split-pea-soup-recipe.html",
    recipe_id: "47960",
    image_url: "http://static.food2fork.com/split_pea_soup_recipedc9c.jpg",
    social_rank: 99.999985445422,
    publisher_url: "http://www.101cookbooks.com",
    title: "Vegetarian Split Pea Soup"
  },
  {
    publisher: "Real Simple",
    f2f_url: "http://food2fork.com/view/39519",
    ingredients: [
      "1 tablespoon olive oil",
      "1 14-ounce package extra-firm tofu, drained, patted dry, and crumbled",
      "1 1/2 teaspoons chili powder",
      "1 kosher salt and black pepper",
      "1 10-ounce package frozen corn (2 cups), thawed",
      "8 5-ounce package baby spinach (about 6 loosely packed cups)",
      "3/4 cup small flour tortillas, warmed",
      "3/4 cup crumbled fresh goat cheese (3 ounces)\n"
    ],
    source_url:
      "http://www.realsimple.com/food-recipes/browse-all-recipes/vegetarian-tacos-spinach-corn-goat-cheese-00000000029612/index.html",
    recipe_id: "39519",
    image_url:
      "http://static.food2fork.com/knifevegetariantacos_300253a792b.jpg",
    social_rank: 99.99988007624458,
    publisher_url: "http://realsimple.com",
    title: "Vegetarian Tacos With Goat Cheese"
  },
  {
    publisher: "All Recipes",
    f2f_url: "http://food2fork.com/view/33863",
    ingredients: [
      "1 1/2 tablespoons vegetable oil",
      "1 small onion, diced",
      "1 teaspoon minced fresh ginger root",
      "4 cloves garlic, minced",
      "2 potatoes, cubed",
      "4 carrots, cubed",
      "1 fresh jalapeno pepper, seeded and sliced",
      "3 tablespoons ground unsalted cashews",
      "1 (4 ounce) can tomato sauce",
      "2 teaspoons salt",
      "1 1/2 tablespoons curry powder",
      "1 cup frozen green peas",
      "1/2 green bell pepper, chopped",
      "1/2 red bell pepper, chopped",
      "1 cup heavy cream",
      "1 bunch fresh cilantro for garnish"
    ],
    source_url: "http://allrecipes.com/Recipe/Vegetarian-Korma/Detail.aspx",
    recipe_id: "33863",
    image_url: "http://static.food2fork.com/11647482cf.jpg",
    social_rank: 99.9996703776198,
    publisher_url: "http://allrecipes.com",
    title: "Vegetarian Korma"
  },
  {
    publisher: "All Recipes",
    f2f_url: "http://food2fork.com/view/33891",
    ingredients: [
      "2 tablespoons vegetable oil",
      "1 (1 pound) package frozen pepper and onion stir fry mix",
      "2 cloves garlic, minced",
      "3 tablespoons ground cumin",
      "1 (28 ounce) can crushed tomatoes",
      "3 (4 ounce) cans chopped green chile peppers, drained",
      "4 (14 ounce) cans vegetable broth",
      "salt and pepper to taste",
      "1 (11 ounce) can whole kernel corn",
      "12 ounces tortilla chips",
      "1 cup shredded Cheddar cheese",
      "1 avocado - peeled, pitted and diced"
    ],
    source_url:
      "http://allrecipes.com/Recipe/Vegetarian-Tortilla-Soup/Detail.aspx",
    recipe_id: "33891",
    image_url: "http://static.food2fork.com/373605e35.jpg",
    social_rank: 99.99962201823132,
    publisher_url: "http://allrecipes.com",
    title: "Vegetarian Tortilla Soup"
  },
  {
    publisher: "Jamie Oliver",
    f2f_url: "http://food2fork.com/view/a7ecf6",
    ingredients: [
      "2 medium-sized sweet potatoes, approximately 500g",
      "1 level teaspoon cayenne pepper, plus extra for sprinkling",
      "1 heaped teaspoon ground cumin, plus extra for sprinkling",
      "1 level teaspoon ground cinnamon, plus extra for sprinkling",
      " olive oil",
      " sea salt",
      " freshly ground black pepper",
      "1 onion",
      "1 red pepper",
      "1 yellow pepper",
      "1 bunch fresh coriander",
      "1 red chilli",
      "1 green chilli",
      "2 cloves garlic",
      "2 x 400 g tinned beans, such as kidney, chickpea, pinto and cannellini",
      "2 x 400 g tinned chopped tomatoes"
    ],
    source_url:
      "http://www.jamieoliver.com/recipes/pulses-recipes/vegetarian-chilli",
    recipe_id: "a7ecf6",
    image_url: "http://static.food2fork.com/642_2_1350913796_lrg49c8.jpg",
    social_rank: 99.99920410614183,
    publisher_url: "http://www.jamieoliver.com",
    title: "Vegetarian chilli"
  },
  {
    publisher: "Cookie and Kate",
    f2f_url: "http://food2fork.com/view/252cb1",
    ingredients: [
      "1 cup dried brown lentils, picked over and rinsed",
      "1 bay leaf",
      "2 cups vegetable broth (or water)",
      "8 ounces cremini mushrooms (or white mushrooms), sliced",
      "½ cup old-fashioned oats",
      "½ cup flat-leaf parsley leaves",
      "1 teaspoon dried oregano",
      "½ teaspoon red pepper flakes",
      "½ teaspoon dried thyme",
      "½ teaspoon dried terragon",
      "2 tablespoons olive oil",
      "1 medium white onion, chopped",
      "3 to 4 garlic cloves, minced",
      "¼ cup red wine",
      "1 tablespoon tamari soy sauce (optional)",
      "2 eggs",
      "sea salt and pepper to taste"
    ],
    source_url: "http://cookieandkate.com/2013/lentil-and-mushroom-meatballs/",
    recipe_id: "252cb1",
    image_url:
      "http://static.food2fork.com/lentilandmushroommeatballs14147.jpg",
    social_rank: 99.9999823706585,
    publisher_url: "http://cookieandkate.com",
    title: "All Recipes"
  },
  {
    publisher: "101 Cookbooks",
    f2f_url: "http://food2fork.com/view/48142",
    ingredients: [
      "2 tablespoons olive oil",
      "1 large yellow onion, chopped",
      "2 shallots, chopped",
      "8 small/med garlic cloves, finely chopped",
      "1 tablespoon ginger, peeled and grated",
      "3 tablespoons chili powder",
      "1 teaspoon ground cumin",
      "1 serrano pepper, seeded and finely chopped",
      "1 chipotle pepper (from can or rehydrate), minced",
      "1 28-ounce can of crushed tomatoes",
      "10 cups vegetable broth",
      "1 1/2 cups cooked chickpeas (canned is fine)",
      "2 1/4 cups black, brown, or green lentils (or combo), rinsed and picked over",
      "2/3 cup pearled barley or pearled farro",
      "2/3 cup bulgur wheat",
      "1 teaspoon fine grain sea salt (or to taste)",
      "toppings (opt): a bit of chopped serranos, a bit of feta or dollop of thinned out salted yogurt, a drizzle of equal parts chopped fresh oregano and olive oil, chopped onion"
    ],
    source_url:
      "http://www.101cookbooks.com/archives/pierce-street-vegetarian-chili-recipe.html",
    recipe_id: "48142",
    image_url: "http://static.food2fork.com/vegetarian_chili_recipe7415.jpg",
    social_rank: 99.99636875646131,
    publisher_url: "http://www.101cookbooks.com",
    title: "Pierce Street Vegetarian Chili"
  },
  {
    publisher: "Cookin Canuck",
    f2f_url: "http://food2fork.com/view/d4ab03",
    ingredients: [
      "1 (1½ lb.) eggplant",
      "1 large zucchini",
      "2 tbsp olive oil",
      "½ tsp kosher salt",
      "½ tsp freshly ground black pepper",
      "3 oz. fresh mozzarella, thinly sliced",
      "1½ cups tomato sauce (your favorite kind)",
      "10 large basil leaves"
    ],
    source_url:
      "http://www.cookincanuck.com/2012/06/grilled-zucchini-eggplant-parmesan-recipe-vegetarian/",
    recipe_id: "d4ab03",
    image_url: "http://static.food2fork.com/7386480724_46c61ced022501.jpg",
    social_rank: 99.99940149992618,
    publisher_url: "http://www.cookincanuck.com",
    title: "Home"
  },
  {
    publisher: "Cookin Canuck",
    f2f_url: "http://food2fork.com/view/612bd1",
    ingredients: [
      "2/3 cup quinoa",
      "1 1/3 cup water",
      "Pinch of salt",
      "2 cups diced (1/2-inch) butternut squash",
      "2 tsp olive oil",
      "1 medium onion, diced",
      "1/2 tsp kosher salt",
      "2 tbsp minced fresh ginger",
      "1/2 large jalapeno pepper, seeds & membranes removed, minced",
      "2 large cloves garlic, minced",
      "1/2 cup lite coconut milk, stirred",
      "1 can (14 oz.) petite diced tomatoes (with juices)",
      "1 can (14 oz.) chickpeas, drained and rinsed",
      "2 green onions, thinly sliced",
      "InstructionsIn a medium saucepan, combine quinoa and water, and place over high heat. Bring the mixture to a boil. Reduce heat to low, cover, and cook for approximately 20 minutes, or until all of the water is absorbed. Remove the quinoa from the heat, fluff with a fork and re-cover to keep warm."
    ],
    source_url:
      "http://www.cookincanuck.com/2011/12/vegetarian-stew-with-quinoa-butternut-squash-coconut-milk-recipe/",
    recipe_id: "612bd1",
    image_url: "http://static.food2fork.com/6469718801_e628da43a65c5c.jpg",
    social_rank: 99.9952349869711,
    publisher_url: "http://www.cookincanuck.com",
    title: "Vegetarian Stew with Quinoa, Butternut Squash & Coconut Milk"
  },
  {
    publisher: "Simply Recipes",
    f2f_url: "http://food2fork.com/view/36991",
    ingredients: [
      "1 1-pound eggplant, cut into 1-inch cubes",
      "Olive oil",
      "2 yellow onions, chopped",
      "3 cloves garlic, minced",
      "2 medium zucchini, chopped",
      "2 large red bell peppers, cored, seeded, diced",
      "1 to 2 jalapeo peppers, seeded, finely minced (Taste and check the heat of the jalapeos. If very hot only use one, if mildly hot, use two. Wash hands with soap and water after handling. Do not rub eyes.)",
      "1 28-ounce can Italian plum tomatoes, coarsely chopped, including liquid (or 2 pounds fresh plum tomatoes, peeled and chopped)",
      "1 Tbsp ground cumin",
      "1-2 Tbsp chili powder",
      "2 Tbsp chopped fresh chopped oregano or 2 teaspoons dried",
      "1 teaspoon fennel seeds",
      "1 1/2 cup cooked white beans (1 15-ounce can, drained and rinsed)",
      "1 1/2 cup cooked kidney beans (1 15-ounce can, drained and rinsed)",
      "Zest of one lemon",
      "3 Tbsp lemon juice",
      "1 teaspoon sugar",
      "1/3 cup chopped fresh cilantro (can sub parsley if you have an aversion to cilantro)",
      "Salt and freshly ground black pepper to taste\n"
    ],
    source_url: "http://www.simplyrecipes.com/recipes/spicy_vegetarian_chili/",
    recipe_id: "36991",
    image_url:
      "http://static.food2fork.com/vegetarianchilinew300x200b7e9cc1d.jpg",
    social_rank: 99.98448061864038,
    publisher_url: "http://simplyrecipes.com",
    title: "Spicy Vegetarian Chili"
  },
  {
    publisher: "BBC Food",
    f2f_url: "http://food2fork.com/view/73593f",
    ingredients: [
      "175g/6oz green lentils",
      "2 tbsp sunflower oil",
      "1 large onion",
      "1-2 cloves garlic",
      "1-2 tsp chilli powder",
      "1 tsp cumin",
      "1 red and 1 green pepper",
      "2 carrots",
      "2 x 400g/14oz cans chopped tomatoes",
      "1 heaped tbsp tomato pure",
      "300ml/ pint vegetable stock",
      "100g/4oz frozen peas",
      "175g/6oz mushrooms",
      "1 courgette",
      "salt and freshly ground black pepper",
      "1 can kidney beans"
    ],
    source_url: "http://www.bbc.co.uk/food/recipes/vegetarianchilli_6544",
    recipe_id: "73593f",
    image_url: "http://static.food2fork.com/vegetarianchilli_6544_16x94e7e.jpg",
    social_rank: 99.9830790504507,
    publisher_url: "http://www.bbc.co.uk/food",
    title: "Vegetarian chilli"
  },
  {
    publisher: "All Recipes",
    f2f_url: "http://food2fork.com/view/33861",
    ingredients: [
      "2 tablespoons olive oil",
      "1 yellow onion, chopped",
      "2 tablespoons chopped garlic",
      "1 bunch kale, stems removed and leaves chopped",
      "8 cups water",
      "6 cubes vegetable bouillon (such as Knorr)",
      "1 (15 ounce) can diced tomatoes",
      "6 white potatoes, peeled and cubed",
      "2 (15 ounce) cans cannellini beans (drained if desired)",
      "1 tablespoon Italian seasoning",
      "2 tablespoons dried parsley",
      "salt and pepper to taste"
    ],
    source_url: "http://allrecipes.com/Recipe/Vegetarian-Kale-Soup/Detail.aspx",
    recipe_id: "33861",
    image_url: "http://static.food2fork.com/9634469d6c.jpg",
    social_rank: 99.95793561845834,
    publisher_url: "http://allrecipes.com",
    title: "Vegetarian Kale Soup"
  },
  {
    publisher: "Cookie and Kate",
    f2f_url: "http://food2fork.com/view/359faf",
    ingredients: [
      "1 medium red onion, chopped",
      "1 green bell pepper, chopped",
      "1 red bell pepper, chopped",
      "1 medium sweet potato, peeled and cut into 12-inch pieces",
      "4 garlic cloves, pressed or minced, or 1 heaping tablespoon of minced garlic",
      "1 tablespoon chili powder",
      "1 teaspoon ground cumin",
      "1 teaspoon cayenne pepper (more or less, depending on how spicy you like your chili)",
      "2 teaspoons unsweetened cocoa powder",
      "¼ teaspoon ground cinnamon",
      "ground sea salt and black pepper",
      "about 28-ounces canned diced tomatoes, including the liquid*",
      "1 can black beans, rinsed and drained",
      "1 can kidney beans, rinsed and drained",
      "about 2 cups OR one 14 oz. can vegetable broth",
      "garnishes: sour cream, sliced scallions, sliced radishes (optional)"
    ],
    source_url: "http://cookieandkate.com/2011/sweet-potato-chili-recipe/",
    recipe_id: "359faf",
    image_url:
      "http://static.food2fork.com/sweetpotatochilirecipe550x3665be1.jpg",
    social_rank: 99.99989206160792,
    publisher_url: "http://cookieandkate.com",
    title: "All Recipes"
  },
  {
    publisher: "Cookin Canuck",
    f2f_url: "http://food2fork.com/view/52b33e",
    ingredients: [
      "The pesto:",
      "1 cup chopped cilantro",
      "1 large garlic clove, minced",
      "1 tbsp minced seeded jalapeno pepper",
      "2 tsp fresh lime juice",
      "Pinch of salt",
      "Pinch of pepper",
      "1/4 cup extra-virgin olive oil",
      "The pizza:",
      "1 medium eggplant, cut into 1/3-inch slices",
      "1 tbsp olive oil",
      "1/2 tsp kosher salt",
      "1/2 tsp freshly ground black pepper",
      "2 pieces naan (whole wheat or regular, store-bought or homemade)",
      "1/4 tsp red chile flakes",
      "2 oz. fresh mozzarella, thinly sliced"
    ],
    source_url:
      "http://www.cookincanuck.com/2012/02/vegetarian-naan-pizza-with-eggplant-cilantro-jalapeno-pesto-recipe/",
    recipe_id: "52b33e",
    image_url: "http://static.food2fork.com/6879227175_6a4e734b2e10e9.jpg",
    social_rank: 99.75172038560316,
    publisher_url: "http://www.cookincanuck.com",
    title: "Vegetarian Eggplant Naan Pizza with Cilantro Jalapeno Pesto"
  },
  {
    publisher: "101 Cookbooks",
    f2f_url: "http://food2fork.com/view/48021",
    ingredients: [
      "1 cup clarified butter (or ghee)",
      "1 cup unbleached all-purpose flour",
      "5 cups yellow onion, chopped into 1/3-inch dice",
      "3/4 cup green bell pepper, chopped into 1/3-inch dice",
      "scant 1/2 teaspoon fine-grain sea salt",
      "1/4 cup garlic, chopped",
      "1/2 teaspoon crushed red pepper flakes",
      "2 dried bay leaves",
      "3-4 quarts of a great tasting vegetable broth (see head notes!)",
      "Gumbo",
      "file'",
      "1 bunch green onions, chopped green ends only",
      "6-8 eggs",
      "5- 6 cups cooked long grain white or brown basmati rice"
    ],
    source_url:
      "http://www.101cookbooks.com/archives/vegetarian-gumbo-recipe.html",
    recipe_id: "48021",
    image_url: "http://static.food2fork.com/vegetarian_gumbo517c.jpg",
    social_rank: 99.68947964670343,
    publisher_url: "http://www.101cookbooks.com",
    title: "Vegetarian Gumbo"
  },
  {
    publisher: "Chow",
    f2f_url: "http://food2fork.com/view/7ac16e",
    ingredients: [
      "1 tablespoon vegetable oil",
      "1 onion, medium dice",
      "1 carrot, medium dice",
      "2 garlic cloves, minced",
      "Kosher salt",
      "Freshly ground black pepper",
      "1 bell pepper, medium dice",
      "1 zucchini, medium dice",
      "2 teaspoons ground cumin",
      "2 tablespoons plus 1 teaspoon chili powder",
      "2 (15-ounce) cans light kidney, dark kidney, or black beans, drained and rinsed",
      "1 1/2 cups water",
      "1 (28-ounce) can chopped tomatoes",
      "Chopped cilantro, for garnish (optional)",
      "Quartered lime pieces, for garnish (optional)",
      "Shredded cheddar cheese or crumbled queso fresco, for garnish (optional)",
      "Sour cream, for garnish (optional)"
    ],
    source_url: "http://www.chow.com/recipes/29192-basic-vegetarian-chili",
    recipe_id: "7ac16e",
    image_url: "http://static.food2fork.com/29192_veggie_chili_620c6e9.jpg",
    social_rank: 99.61530324248194,
    publisher_url: "http://www.chow.com",
    title: "Basic Vegetarian Chili Recipe"
  },
  {
    publisher: "All Recipes",
    f2f_url: "http://food2fork.com/view/17284",
    ingredients: [
      "1 tablespoon vegetable oil",
      "1 cup chopped onions",
      "3/4 cup chopped carrots",
      "3 cloves garlic, minced",
      "1 cup chopped green bell pepper",
      "1 cup chopped red bell pepper",
      "3/4 cup chopped celery",
      "1 tablespoon chili powder",
      "1 1/2 cups chopped fresh mushrooms",
      "1 (28 ounce) can whole peeled tomatoes with liquid, chopped",
      "1 (19 ounce) can kidney beans with liquid",
      "1 (11 ounce) can whole kernel corn, undrained",
      "1 tablespoon ground cumin",
      "1 1/2 teaspoons dried oregano",
      "1 1/2 teaspoons dried basil"
    ],
    source_url:
      "http://allrecipes.com/Recipe/Insanely-Easy-Vegetarian-Chili/Detail.aspx",
    recipe_id: "17284",
    image_url: "http://static.food2fork.com/10051c8df.jpg",
    social_rank: 99.29058770781617,
    publisher_url: "http://allrecipes.com",
    title: "Insanely Easy Vegetarian Chili"
  },
  {
    publisher: "Epicurious",
    f2f_url: "http://food2fork.com/view/5c5210",
    ingredients: [
      "10 ounces pearl onions (about 2 1/4 cups)",
      "9 tablespoon olive oil, divided",
      "1 1/2 pounds seitan, sliced 1/4 inch thick and patted dry",
      "3 medium leeks (white and pale green parts only), halved lengthwise, sliced 1/2 inch thick, and ",
      "3 garlic cloves, chopped",
      "1 pound cremini mushrooms, trimmed and quartered",
      "3/4 pound carrots (about 4 medium), cut into 3/4-inch-thick pieces",
      "3/4 pound parsnips (about 4 medium), cut into 3/4-inch-thick pieces",
      "2 tablespoons thyme leaves",
      "1 tablespoon chopped rosemary",
      "1 (750-ml) bottle full-bodied red wine such as Burgundy or Ctes du Rhne ",
      "3 tablespoons unsalted butter, softened",
      "3 tablespoons all-purpose flour",
      "3 1/2 cups hot ",
      "1/2 cup chopped flat-leaf parsley",
      "2 1/2 pounds Yukon Gold potatoes",
      "3/4 pound celery root, peeled and cut into 1-inch pieces",
      "1/2 stick unsalted butter",
      "1/2 cup whole milk",
      "1/2 cup heavy cream",
      "Equipment: a 3-quart shallow (2-inch-deep) flameproof baking dish; a potato ricer or a food mill fitted with medium disk"
    ],
    source_url:
      "http://www.epicurious.com/recipes/food/views/Vegetarian-Shepherds-Pie-355994",
    recipe_id: "5c5210",
    image_url: "http://static.food2fork.com/3559944618.jpg",
    social_rank: 99.15079920574989,
    publisher_url: "http://www.epicurious.com",
    title: "Vegetarian Shepherd's Pie"
  },
  {
    publisher: "All Recipes",
    f2f_url: "http://food2fork.com/view/30996",
    ingredients: [
      "1/2 cup uncooked white rice",
      "3/4 cup water",
      "4 green bell peppers",
      "1 onion, chopped",
      "4 tablespoons olive oil",
      "8 ounces textured vegetable protein",
      "2 tablespoons chopped fresh parsley",
      "2 cups tomato sauce",
      "4 ounces shredded mozzarella cheese",
      "salt to taste",
      "ground black pepper to taste"
    ],
    source_url: "http://allrecipes.com/Recipe/Stuffed-Peppers/Detail.aspx",
    recipe_id: "30996",
    image_url: "http://static.food2fork.com/13686616a4.jpg",
    social_rank: 99.0071239458231,
    publisher_url: "http://allrecipes.com",
    title: "Vegetarian Stuffed Peppers"
  },
  {
    publisher: "Chow",
    f2f_url: "http://food2fork.com/view/30cdd2",
    ingredients: [
      "1 cup pitted mixed olives such as Picholine, Cerignola, or Nioise, coarsely chopped",
      "1/4 cup extra-virgin olive oil",
      "2 tablespoons finely chopped Italian parsley",
      "1 tablespoon minced shallot",
      "2 teaspoons finely chopped fresh or 1 teaspoon dried oregano",
      "1 garlic clove, minced",
      "2 roasted red peppers, seeded and sliced into 1/2-inch-thick strips",
      "3/4 cup coarsely chopped marinated artichoke hearts",
      "3/4 cup stemmed and sliced pepperoncini",
      "1 tablespoon extra-virgin olive oil",
      "2 medium portobello mushrooms, cleaned and sliced into 1/2-inch-wide strips",
      "4 teaspoons balsamic vinegar",
      "1 (1-pound) loaf ciabatta, sliced in half horizontally, insides removed, and toasted",
      "4 thin slices provolone cheese (about 4 ounces)"
    ],
    source_url: "http://www.chow.com/recipes/28015-vegetarian-muffuletta",
    recipe_id: "30cdd2",
    image_url:
      "http://static.food2fork.com/28015_vegetarian_muffuletta_60058d9.jpg",
    social_rank: 98.94606405256211,
    publisher_url: "http://www.chow.com",
    title: "Vegetarian Muffuletta Recipe"
  }
];
